1/rails-example-project/config/routes.rb
Rails.application.routes.draw do
  root 'presses#new'

  resources :presses, except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

1/rails-example-project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

1/rails-example-project/app/models/press.rb
class Press < ApplicationRecord
end

1/rails-example-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

1/rails-example-project/app/controllers/presses_controller.rb
class PressesController < ApplicationController
  before_action :set_press, only: [:show, :edit, :update, :destroy]

  # GET /presses
  # GET /presses.json
  def index
    @presses = Press.all
  end

  # GET /presses/1
  # GET /presses/1.json
  def show
  end

  # GET /presses/new
  def new
    @press = Press.new
    @count = Press.count
  end

  # GET /presses/1/edit
  def edit
  end

  # POST /presses
  # POST /presses.json
  def create
    @press = Press.new(press_params)

    respond_to do |format|
      if @press.save
        format.html { redirect_to new_press_path, notice: 'Press was successfully created.' }
        format.json { render :show, status: :created, location: @press }
      else
        format.html { render :new }
        format.json { render json: @press.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presses/1
  # PATCH/PUT /presses/1.json
  def update
    respond_to do |format|
      if @press.update(press_params)
        format.html { redirect_to @press, notice: 'Press was successfully updated.' }
        format.json { render :show, status: :ok, location: @press }
      else
        format.html { render :edit }
        format.json { render json: @press.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presses/1
  # DELETE /presses/1.json
  def destroy
    @press.destroy
    respond_to do |format|
      format.html { redirect_to presses_url, notice: 'Press was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_press
      @press = Press.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def press_params
      params.fetch(:press, {})
    end
end

1/rails-example-project/app/helpers/application_helper.rb
module ApplicationHelper
end

1/rails-example-project/app/helpers/presses_helper.rb
module PressesHelper
end

1/rails-example-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

1/rails-example-project/app/views/presses/_form.html.erb
<%= form_with(model: press, local: true) do |form| %>
  <% if press.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(press.errors.count, "error") %> prohibited this press from being saved:</h2>

      <ul>
      <% press.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="actions">
    <%= form.submit 'Press' %>
  </div>
<% end %>

1/rails-example-project/app/views/presses/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= pluralize(@presses.count, 'press')%></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presses.reverse.each do |press| %>
      <tr>
        <td><%= link_to press.created_at, press %> </td>
        <td><%= link_to 'Destroy', press, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Press more', new_press_path %>

1/rails-example-project/app/views/presses/new.html.erb
<h1>New Press</h1>

<p> Total presses: <%= @count %> </p>

<p id="notice"><%= notice %></p>

<%= render 'form', press: @press %>

<%= link_to 'List presses', presses_path %>

1/rails-example-project/app/views/presses/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Pressed at: <%= @press.created_at %> </h1>

<%= link_to 'Press more', new_press_path %>
<%= link_to 'List presses', presses_path %>